export type SupportedLanguage =
  | 'en'
  | 'hi'
  | 'bn'
  | 'te'
  | 'mr'
  | 'ta'
  | 'ur'
  | 'gu'
  | 'kn'
  | 'ml'
  | 'or'
  | 'pa'
  | 'as';

export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  region: string;
  flagOrIcon: string;
}

export const INDIAN_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'Pan-India / International', flagOrIcon: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'North & Central India', flagOrIcon: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'West Bengal, Tripura, Assam', flagOrIcon: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'Andhra Pradesh, Telangana', flagOrIcon: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'Maharashtra, Goa', flagOrIcon: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'Tamil Nadu, Puducherry', flagOrIcon: '🇮🇳' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'Telangana, UP, Delhi, Bihar', flagOrIcon: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'Gujarat, Daman & Diu', flagOrIcon: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'Karnataka', flagOrIcon: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'Kerala, Lakshadweep', flagOrIcon: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'Odisha', flagOrIcon: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'Punjab, Haryana, Delhi', flagOrIcon: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam', flagOrIcon: '🇮🇳' },
];

// High-frequency UI words translated across all 13 Indian languages
export const MULTILINGUAL_DICTIONARY: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'brand.title': 'BeeSure',
    'brand.tagline': 'Traceable Pure Honey from Hive to Home',
    'nav.home': 'Home',
    'nav.marketplace': 'Marketplace',
    'nav.verify': 'Verify QR',
    'nav.dashboard': 'Dashboard',
    'nav.adminConsole': 'Admin Console',
    'nav.myHives': 'My Hives',
    'nav.listings': 'My Listings',
    'nav.orders': 'Orders',
    'nav.labPortal': 'Lab Portal',
    'nav.searchRegion': 'Search State/District',
    'action.buyNow': 'Buy Now',
    'action.addToCart': 'Add to Cart',
    'action.checkout': 'Proceed to Checkout',
    'action.verify': 'Verify',
    'action.details': 'Details',
    'action.cancel': 'Cancel',
    'action.close': 'Close',
    'action.save': 'Save',
    'action.filter': 'Filter',
    'action.search': 'Search...',
    'role.admin': 'Admin',
    'role.beekeeper': 'Beekeeper',
    'role.lab': 'Accredited Lab',
    'role.consumer': 'Consumer',
    'market.pure': '100% PURE',
    'market.inStock': 'In Stock',
    'market.outOfStock': 'Out of Stock',
    'cart.title': 'Your Honey Basket',
  },
  hi: {
    'brand.title': 'बीश्योर (BeeSure)',
    'brand.tagline': 'छत्ते से घर तक शुद्ध व प्रमाणित शहद',
    'nav.home': 'मुख्य पृष्ठ',
    'nav.marketplace': 'बाज़ार (मार्केटप्लेस)',
    'nav.verify': 'क्यूआर सत्यापन',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.adminConsole': 'प्रशासक कंसोल',
    'nav.myHives': 'मेरे छत्ते (Hives)',
    'nav.listings': 'मेरी लिस्टिंग',
    'nav.orders': 'ऑर्डर ट्रैकिंग',
    'nav.labPortal': 'लैब पोर्टल',
    'nav.searchRegion': 'राज्य/ज़िला खोजें',
    'action.buyNow': 'अभी खरीदें',
    'action.addToCart': 'कार्ट में जोड़ें',
    'action.checkout': 'भुगतान की ओर बढ़ें',
    'action.verify': 'सत्यापित करें',
    'action.details': 'विवरण',
    'action.cancel': 'रद्द करें',
    'action.close': 'बंद करें',
    'action.save': 'सहेजें',
    'action.filter': 'फ़िल्टर',
    'action.search': 'खोजें...',
    'role.admin': 'प्रशासक (Admin)',
    'role.beekeeper': 'मधुमक्खी पालक',
    'role.lab': 'प्रमाणित प्रयोगशाला',
    'role.consumer': 'उपभोक्ता',
    'market.pure': '१००% शुद्ध',
    'market.inStock': 'स्टॉक में उपलब्ध',
    'market.outOfStock': 'स्टॉक समाप्त',
    'cart.title': 'आपकी शहद टोकरी',
  },
  bn: {
    'brand.title': 'বীসিওর (BeeSure)',
    'brand.tagline': 'মৌচাক থেকে বাড়ি পর্যন্ত খাঁটি ও নির্ভরযোগ্য মধু',
    'nav.home': 'মূল পাতা',
    'nav.marketplace': 'মধু বাজার (Marketplace)',
    'nav.verify': 'QR যাচাইকরণ',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.adminConsole': 'অ্যাডমিন কনসোল',
    'nav.myHives': 'আমার মৌচাক (Hives)',
    'nav.listings': 'আমার তালিকা',
    'nav.orders': 'অর্ডার ট্র্যাকিং',
    'nav.labPortal': 'ল্যাব পোর্টাল',
    'nav.searchRegion': 'রাজ্য/জেলা অনুসন্ধান',
    'action.buyNow': 'এখনই কিনুন',
    'action.addToCart': 'কার্টে যোগ করুন',
    'action.checkout': 'চেকআউট করুন',
    'action.verify': 'যাচাই করুন',
    'action.details': 'বিস্তারিত',
    'action.cancel': 'বাতিল',
    'action.close': 'বন্ধ করুন',
    'action.save': 'সংরক্ষণ করুন',
    'action.filter': 'ফিল্টার',
    'action.search': 'অনুসন্ধান...',
    'role.admin': 'প্রশাসক',
    'role.beekeeper': 'মৌমাছি পালনকারী',
    'role.lab': 'পরীক্ষাগার (Lab)',
    'role.consumer': 'ভোক্তা / ক্রেতা',
    'market.pure': '১০০% খাঁটি',
    'market.inStock': 'মজুদ আছে',
    'market.outOfStock': 'মজুদ শেষ',
    'cart.title': 'আপনার মধুর ঝুড়ি',
  },
  te: {
    'brand.title': 'బీష్యూర్ (BeeSure)',
    'brand.tagline': 'తేనెటీగల తుట్టె నుండి మీ ఇంటి వరకు స్వచ్ఛమైన తేనె',
    'nav.home': 'హోమ్',
    'nav.marketplace': 'మార్కెట్ ప్లేస్',
    'nav.verify': 'QR ధృవీకరణ',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.adminConsole': 'అడ్మిన్ కన్సోల్',
    'nav.myHives': 'నా తేనెటీగల తుట్టెలు',
    'nav.listings': 'నా లిస్టింగ్‌లు',
    'nav.orders': 'ఆర్డర్ల ట్రాకింగ్',
    'nav.labPortal': 'ల్యాబ్ పోర్టల్',
    'nav.searchRegion': 'రాష్ట్రం/జిల్లా వెతకండి',
    'action.buyNow': 'ఇప్పుడే కొనండి',
    'action.addToCart': 'కార్ట్‌కు జోడించండి',
    'action.checkout': 'చెల్లింపుకు వెళ్లండి',
    'action.verify': 'ధృవీకరించండి',
    'action.details': 'వివరాలు',
    'action.cancel': 'రద్దు చేయండి',
    'action.close': 'మూసివేయి',
    'action.save': 'భద్రపరచండి',
    'action.filter': 'ఫిల్టర్',
    'action.search': 'శోధించండి...',
    'role.admin': 'అడ్మినిస్ట్రేటర్',
    'role.beekeeper': 'తేనెటీగల పెంపకందారుడు',
    'role.lab': 'ల్యాబొరేటరీ',
    'role.consumer': 'వినియోగదారుడు',
    'market.pure': '100% స్వచ్ఛమైనది',
    'market.inStock': 'స్టాక్ అందుబాటులో ఉంది',
    'market.outOfStock': 'స్టాక్ అయిపోయింది',
    'cart.title': 'మీ తేనె బుట్ట',
  },
  mr: {
    'brand.title': 'बीश्योर (BeeSure)',
    'brand.tagline': 'पोळ्यापासून घरापर्यंत शुद्ध आणि प्रमाणित मध',
    'nav.home': 'मुख्यपृष्ठ',
    'nav.marketplace': 'मध बाजारपेठ',
    'nav.verify': 'QR पडताळणी',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.adminConsole': 'अ‍ॅडमिन कन्सोल',
    'nav.myHives': 'माझी मधमाशी पोळी',
    'nav.listings': 'माझी यादी',
    'nav.orders': 'ऑर्डर ट्रॅकिंग',
    'nav.labPortal': 'लॅब पोर्टल',
    'nav.searchRegion': 'राज्य/जिल्हा शोधा',
    'action.buyNow': 'आता खरेदी करा',
    'action.addToCart': 'कार्टमध्ये जोडा',
    'action.checkout': 'खरेदी पूर्ण करा',
    'action.verify': 'पडताळणी करा',
    'action.details': 'तपशील',
    'action.cancel': 'रद्द करा',
    'action.close': 'बंद करा',
    'action.save': 'जतन करा',
    'action.filter': 'फिल्टर',
    'action.search': 'शोधा...',
    'role.admin': 'प्रशासक',
    'role.beekeeper': 'मधमाशी पालक',
    'role.lab': 'मान्यताप्राप्त प्रयोगशाळा',
    'role.consumer': 'ग्राहक',
    'market.pure': '१००% शुद्ध',
    'market.inStock': 'उपलब्ध आहे',
    'market.outOfStock': 'संपले आहे',
    'cart.title': 'तुमची मधाची टोपली',
  },
  ta: {
    'brand.title': 'பீஷ்யூர் (BeeSure)',
    'brand.tagline': 'தேன்கூட்டிலிருந்து உங்கள் இல்லம் வரை தூய தேன்',
    'nav.home': 'முகப்பு',
    'nav.marketplace': 'தேன் சந்தை (Marketplace)',
    'nav.verify': 'QR சரிபார்ப்பு',
    'nav.dashboard': 'முகப்பு பலகை',
    'nav.adminConsole': 'நிர்வாக கன்சோல்',
    'nav.myHives': 'எனது தேன்கூடுகள்',
    'nav.listings': 'எனது பட்டியல்கள்',
    'nav.orders': 'ஆர்டர் கண்காணிப்பு',
    'nav.labPortal': 'ஆய்வக போர்டல்',
    'nav.searchRegion': 'மாநிலம்/மாவட்டம் தேடுக',
    'action.buyNow': 'உடனே வாங்குக',
    'action.addToCart': 'கூடையில் சேர்க்க',
    'action.checkout': 'செக் அவுட் செய்க',
    'action.verify': 'சரிபார்க்கவும்',
    'action.details': 'விவரங்கள்',
    'action.cancel': 'ரத்து செய்க',
    'action.close': 'மூடுக',
    'action.save': 'சேமிக்க',
    'action.filter': 'வடிகட்டுக',
    'action.search': 'தேடுக...',
    'role.admin': 'நிர்வாகி',
    'role.beekeeper': 'தேனீ வளர்ப்பாளர்',
    'role.lab': 'அங்கீகரிக்கப்பட்ட ஆய்வகம்',
    'role.consumer': 'நுகர்வோர் / வாடிக்கையாளர்',
    'market.pure': '100% தூய்மையானது',
    'market.inStock': 'இருப்பில் உள்ளது',
    'market.outOfStock': 'கையிருப்பில் இல்லை',
    'cart.title': 'உங்கள் தேன் கூடை',
  },
  ur: {
    'brand.title': 'بی شیور (BeeSure)',
    'brand.tagline': 'چھتے سے گھر تک خالص اور مصدقہ شہد',
    'nav.home': 'مرکزی صفحہ',
    'nav.marketplace': 'مارکیٹ پلیس',
    'nav.verify': 'کیو آر تصدیق',
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.adminConsole': 'ایڈمن کنسول',
    'nav.myHives': 'میرے چھتے',
    'nav.listings': 'میری فہرستیں',
    'nav.orders': 'آرڈرز کی تفاصیل',
    'nav.labPortal': 'لیب پورٹل',
    'nav.searchRegion': 'ریاست/ضلع تلاش کریں',
    'action.buyNow': 'ابھی خریدیں',
    'action.addToCart': 'کارٹ میں شامل کریں',
    'action.checkout': 'چیک آؤٹ کریں',
    'action.verify': 'تصدیق کریں',
    'action.details': 'تفصیلات',
    'action.cancel': 'منسوخ کریں',
    'action.close': 'بند کریں',
    'action.save': 'محفوظ کریں',
    'action.filter': 'فلٹر',
    'action.search': 'تلاش کریں...',
    'role.admin': 'منتظم (ایڈمن)',
    'role.beekeeper': 'شہد کی مکھیاں پالنے والا',
    'role.lab': 'مصدقہ لیبارٹری',
    'role.consumer': 'صارف / گاہک',
    'market.pure': '۱۰۰٪ خالص',
    'market.inStock': 'دستیاب ہے',
    'market.outOfStock': 'ختم ہوچکا ہے',
    'cart.title': 'آپ کی شہد کی ٹوکری',
  },
  gu: {
    'brand.title': 'બીશ્યોર (BeeSure)',
    'brand.tagline': 'મધપૂડાથી ઘર સુધી શુદ્ધ અને પ્રમાણિત મધ',
    'nav.home': 'મુખ્ય પૃષ્ઠ',
    'nav.marketplace': 'મધ બજાર',
    'nav.verify': 'QR ચકાસણી',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.adminConsole': 'એડમિન કન્સોલ',
    'nav.myHives': 'મારા મધપૂડા',
    'nav.listings': 'મારી યાદી',
    'nav.orders': 'ઓર્ડર ટ્રેકિંગ',
    'nav.labPortal': 'લેબ પોર્ટલ',
    'nav.searchRegion': 'રાજ્ય/જિલ્લો શોધો',
    'action.buyNow': 'હમણાં ખરીદો',
    'action.addToCart': 'કાર્ટમાં ઉમેરો',
    'action.checkout': 'ચેકઆઉટ કરો',
    'action.verify': 'ચકાસો',
    'action.details': 'વિગતો',
    'action.cancel': 'રદ કરો',
    'action.close': 'બંધ કરો',
    'action.save': 'સાચવો',
    'action.filter': 'ફિલ્ટર',
    'action.search': 'શોધો...',
    'role.admin': 'સંચાલક (Admin)',
    'role.beekeeper': 'મધમાખી પાલક',
    'role.lab': 'લેબોરેટરી',
    'role.consumer': 'ગ્રાહક',
    'market.pure': '૧૦૦% શુદ્ધ',
    'market.inStock': 'સ્ટોકમાં ઉપલબ્ધ',
    'market.outOfStock': 'સ્ટોક ખાલી',
    'cart.title': 'તમારી મધની ટોપલી',
  },
  kn: {
    'brand.title': 'ಬೀಶೂರ್ (BeeSure)',
    'brand.tagline': 'ಜೇನುಗೂಡಿನಿಂದ ನಿಮ್ಮ ಮನೆಗೆ ಶುದ್ಧ ಮತ್ತು ಪ್ರಮಾಣೀಕೃತ ಜೇನುತುಪ್ಪ',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.marketplace': 'ಮಾರುಕಟ್ಟೆ (Marketplace)',
    'nav.verify': 'QR ಪರಿಶೀಲನೆ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.adminConsole': 'ನಿರ್ವಾಹಕ ಕನ್ಸೋಲ್',
    'nav.myHives': 'ನನ್ನ ಜೇನುಪೆಟ್ಟಿಗೆಗಳು',
    'nav.listings': 'ನನ್ನ ಪಟ್ಟಿಗಳು',
    'nav.orders': 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    'nav.labPortal': 'ಪ್ರಯೋಗಾಲಯ ಪೋರ್ಟಲ್',
    'nav.searchRegion': 'ರಾಜ್ಯ/ಜಿಲ್ಲೆ ಹುಡುಕಿ',
    'action.buyNow': 'ಈಗಲೇ ಖರೀದಿಸಿ',
    'action.addToCart': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    'action.checkout': 'ಪಾವತಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    'action.verify': 'ಪರಿಶೀಲಿಸಿ',
    'action.details': 'ವಿವರಗಳು',
    'action.cancel': 'ರದ್ದುಮಾಡಿ',
    'action.close': 'ಮುಚ್ಚಿ',
    'action.save': 'ಉಳಿಸಿ',
    'action.filter': 'ಫಿಲ್ಟರ್',
    'action.search': 'ಹುಡುಕಿ...',
    'role.admin': 'ನಿರ್ವಾಹಕ',
    'role.beekeeper': 'ಜೇನು ಕೃಷಿಕ',
    'role.lab': 'ಮಾನ್ಯತೆ ಪಡೆದ ಲ್ಯಾಬ್',
    'role.consumer': 'ಗ್ರಾಹಕರು',
    'market.pure': '100% ಶುದ್ಧ',
    'market.inStock': 'ದಾಸ್ತಾನು ಲಭ್ಯವಿದೆ',
    'market.outOfStock': 'ಖಾಲಿಯಾಗಿದೆ',
    'cart.title': 'ನಿಮ್ಮ ಜೇನಿನ ಬುಟ್ಟಿ',
  },
  ml: {
    'brand.title': 'ബീഷ്യൂർ (BeeSure)',
    'brand.tagline': 'തേൻകൂട്ടിൽ നിന്ന് നിങ്ങളുടെ വീട്ടിലേക്ക് ശുദ്ധമായ തേൻ',
    'nav.home': 'ഹോം',
    'nav.marketplace': 'തേൻ വിപണി',
    'nav.verify': 'QR പരിശോധന',
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.adminConsole': 'അഡ്മിൻ കൺസോൾ',
    'nav.myHives': 'എന്റെ തേൻകൂടുകൾ',
    'nav.listings': 'എന്റെ ഉൽപ്പന്നങ്ങൾ',
    'nav.orders': 'ഓർഡർ ട്രാക്കിംഗ്',
    'nav.labPortal': 'ലാബ് പോർട്ടൽ',
    'nav.searchRegion': 'സംസ്ഥാനം/ജില്ല തിരയുക',
    'action.buyNow': 'ഇപ്പോൾ വാങ്ങുക',
    'action.addToCart': 'കാർട്ടിലേക്ക് ചേർക്കുക',
    'action.checkout': 'ചെക്ക്ഔട്ട് ചെയ്യുക',
    'action.verify': 'പരിശോധിക്കുക',
    'action.details': 'വിശദാംശങ്ങൾ',
    'action.cancel': 'റദ്ദാക്കുക',
    'action.close': 'അടയ്ക്കുക',
    'action.save': 'സൂക്ഷിക്കുക',
    'action.filter': 'ഫിൽട്ടർ',
    'action.search': 'തിരയുക...',
    'role.admin': 'അഡ്മിനിസ്ട്രേറ്റർ',
    'role.beekeeper': 'തേനീച്ച കർഷകൻ',
    'role.lab': 'അംഗീകൃത ലാബ്',
    'role.consumer': 'ഉപഭോക്താവ്',
    'market.pure': '100% ശുദ്ധം',
    'market.inStock': 'ലഭ്യമാണ്',
    'market.outOfStock': 'തീർന്നുപോയി',
    'cart.title': 'നിങ്ങളുടെ തേൻ കൊട്ട',
  },
  or: {
    'brand.title': 'ବିଶ୍ୟୋର (BeeSure)',
    'brand.tagline': 'ମହୁଫେଣାରୁ ଘର ପର୍ଯ୍ୟନ୍ତ ଶୁଦ୍ଧ ଓ ପ୍ରମାଣିତ ମହୁ',
    'nav.home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
    'nav.marketplace': 'ମହୁ ବଜାର',
    'nav.verify': 'QR ଯାଞ୍ଚ',
    'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'nav.adminConsole': 'ଆଡମିନ କନସୋଲ',
    'nav.myHives': 'ମୋର ମହୁବାକ୍ସ',
    'nav.listings': 'ମୋର ତାଲିକା',
    'nav.orders': 'ଅର୍ଡର ଟ୍ରାକିଂ',
    'nav.labPortal': 'ଲ୍ୟାବ ପୋର୍ଟାଲ',
    'nav.searchRegion': 'ରାଜ୍ୟ/ଜିଲ୍ଲା ଖୋଜନ୍ତୁ',
    'action.buyNow': 'ବର୍ତ୍ତମାନ କିଣନ୍ତୁ',
    'action.addToCart': 'କାର୍ଟରେ ଯୋଡନ୍ତୁ',
    'action.checkout': 'ଚେକଆଉଟ କରନ୍ତୁ',
    'action.verify': 'ଯାଞ୍ଚ କରନ୍ତୁ',
    'action.details': 'ବିବରଣୀ',
    'action.cancel': 'ବାତିଲ କରନ୍ତୁ',
    'action.close': 'ବନ୍ଦ କରନ୍ତୁ',
    'action.save': 'ସାଇତନ୍ତୁ',
    'action.filter': 'ଫିଲ୍ଟର',
    'action.search': 'ଖୋଜନ୍ତୁ...',
    'role.admin': 'ପ୍ରଶାସକ (Admin)',
    'role.beekeeper': 'ମହୁଚାଷୀ',
    'role.lab': 'ସ୍ୱୀକୃତିପ୍ରାପ୍ତ ଲ୍ୟାବ',
    'role.consumer': 'ଗ୍ରାହକ',
    'market.pure': '୧୦୦% ଶୁଦ୍ଧ',
    'market.inStock': 'ଉପଲବ୍ଧ ଅଛି',
    'market.outOfStock': 'ଶେଷ ହୋଇଯାଇଛି',
    'cart.title': 'ଆପଣଙ୍କ ମହୁ ଟୋକେଇ',
  },
  pa: {
    'brand.title': 'ਬੀਸਿਓਰ (BeeSure)',
    'brand.tagline': 'ਮਧੂਮੱਖੀ ਦੇ ਛੱਤੇ ਤੋਂ ਘਰ ਤੱਕ ਸ਼ੁੱਧ ਅਤੇ ਪ੍ਰਮਾਣਿਤ ਸ਼ਹਿਦ',
    'nav.home': 'ਮੁੱਖ ਪੰਨਾ',
    'nav.marketplace': 'ਸ਼ਹਿਦ ਮੰਡੀ (Marketplace)',
    'nav.verify': 'QR ਜਾਂਚ',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.adminConsole': 'ਐਡਮਿਨ ਕੰਸੋਲ',
    'nav.myHives': 'ਮੇਰੇ ਮਧੂਮੱਖੀ ਡੱਬੇ (Hives)',
    'nav.listings': 'ਮੇਰੀਆਂ ਸੂਚੀਆਂ',
    'nav.orders': 'ਆਰਡਰ ਟਰੈਕਿੰਗ',
    'nav.labPortal': 'ਲੈਬ ਪੋਰਟਲ',
    'nav.searchRegion': 'ਰਾਜ/ਜ਼ਿਲ੍ਹਾ ਖੋਜੋ',
    'action.buyNow': 'ਹੁਣੇ ਖਰੀਦੋ',
    'action.addToCart': 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    'action.checkout': 'ਭੁਗਤਾਨ ਵੱਲ ਵਧੋ',
    'action.verify': 'ਤਸਦੀਕ ਕਰੋ',
    'action.details': 'ਵੇਰਵੇ',
    'action.cancel': 'ਰੱਦ ਕਰੋ',
    'action.close': 'ਬੰਦ ਕਰੋ',
    'action.save': 'ਸੰਭਾਲੋ',
    'action.filter': 'ਫਿਲਟਰ',
    'action.search': 'ਖੋਜੋ...',
    'role.admin': 'ਪ੍ਰਬੰਧਕ (Admin)',
    'role.beekeeper': 'ਮਧੂਮੱਖੀ ਪਾਲਕ',
    'role.lab': 'ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਲੈਬ',
    'role.consumer': 'ਗਾਹਕ',
    'market.pure': '੧੦੦% ਸ਼ੁੱਧ',
    'market.inStock': 'ਸਟਾਕ ਵਿੱਚ ਉਪਲਬਧ',
    'market.outOfStock': 'ਸਟਾਕ ਮੁੱਕ ਗਿਆ',
    'cart.title': 'ਤੁਹਾਡੀ ਸ਼ਹਿਦ ਦੀ ਟੋਕਰੀ',
  },
  as: {
    'brand.title': 'বিছিঅ’ৰ (BeeSure)',
    'brand.tagline': 'মৌচাকৰ পৰা ঘৰলৈকে বিশুদ্ধ আৰু প্ৰমাণিত মৌ',
    'nav.home': 'মুখ্য পৃষ্ঠা',
    'nav.marketplace': 'মৌ বজাৰ (Marketplace)',
    'nav.verify': 'QR পৰীক্ষণ',
    'nav.dashboard': 'ডেশ্বব’ৰ্ড',
    'nav.adminConsole': 'এডমিন কনচ’ল',
    'nav.myHives': 'মোৰ মৌচাক (Hives)',
    'nav.listings': 'মোৰ তালিকা',
    'nav.orders': 'অৰ্ডাৰ ট্ৰেকিং',
    'nav.labPortal': 'লেব প’ৰ্টেল',
    'nav.searchRegion': 'ৰাজ্য/জিলা সন্ধান',
    'action.buyNow': 'এতিয়াই কিনক',
    'action.addToCart': 'কাৰ্টত যোগ কৰক',
    'action.checkout': 'চেকআউট কৰক',
    'action.verify': 'পৰীক্ষা কৰক',
    'action.details': 'বিৱৰণ',
    'action.cancel': 'বাতিল কৰক',
    'action.close': 'বন্ধ কৰক',
    'action.save': 'সংৰক্ষণ কৰক',
    'action.filter': 'ফিল্টাৰ',
    'action.search': 'সন্ধান কৰক...',
    'role.admin': 'প্ৰশাসক',
    'role.beekeeper': 'মৌপালক',
    'role.lab': 'প্ৰমাণিত পৰীক্ষাগাৰ',
    'role.consumer': 'গ্ৰাহক',
    'market.pure': '১০০% বিশুদ্ধ',
    'market.inStock': 'মজুত আছে',
    'market.outOfStock': 'মজুত শেষ',
    'cart.title': 'আপোনাৰ মৌৰ পাচি',
  },
};
